
const FETCH_PLAYERS_LIST = 'FETCH_PLAYERS_LIST';
const FETCH_PLAYERS_LIST_SUCCESS = 'FETCH_PLAYERS_LIST_SUCCESS';
const FETCH_PLAYERS_LIST_FAILURE = 'FETCH_PLAYERS_LIST_FAILURE';

const FETCH_PLAYER_INFO = 'FETCH_PLAYER_INFO';
const FETCH_PLAYER_INFO_SUCCESS = 'FETCH_PLAYER_INFO_SUCCESS';
const FETCH_PLAYER_INFO_FAILURE = 'FETCH_PLAYER_INFO_FAILURE';

const FETCH_PLAYER_STATS = 'FETCH_PLAYER_STATS';
const FETCH_PLAYER_STATS_SUCCESS = 'FETCH_PLAYER_STATS_SUCCESS';
const FETCH_PLAYER_STATS_FAILURE = 'FETCH_PLAYER_STATS_FAILURE';

export default {
  FETCH_PLAYERS_LIST,
  FETCH_PLAYERS_LIST_SUCCESS,
  FETCH_PLAYERS_LIST_FAILURE,
  FETCH_PLAYER_INFO,
  FETCH_PLAYER_INFO_SUCCESS,
  FETCH_PLAYER_INFO_FAILURE,
  FETCH_PLAYER_STATS,
  FETCH_PLAYER_STATS_SUCCESS,
  FETCH_PLAYER_STATS_FAILURE
}